language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"      # current default Python on Travis CI
    - "3.7"
    - "3.8"

services:
    - docker

before_script: pip install docker-compose

script:
    -docker-compose run --rm app sh -c "python manage.py test && flake8"